### ISSUE TITLE
После подключения и активации ошибки

### ISSUE THREAD

**Issue by lustmordtheblackpost** [yandex-money/yandex-money-ycms-v2-webasyst#10]
```
Query Error 0: 
Query: code 0
## wa-system/database/waModel.class.php(257)
#0 wa-system/database/waModel.class.php(357): waModel->run(NULL)
#1 wa-apps/shop/plugins/yamodule_api/lib/config/install.php(27): waModel->query(NULL)
#2 wa-system/plugin/waPlugin.class.php(166): include('/home/s/seoshek...')
#3 wa-system/plugin/waPlugin.class.php(70): waPlugin->install()
#4 wa-system/plugin/waPlugin.class.php(41): waPlugin->checkUpdates()
#5 wa-system/waSystem.class.php(1361): waPlugin->__construct(Array)
#6 wa-system/controller/waFrontController.class.php(156): waSystem->getPlugin('yamodule_api', true)
#7 wa-system/controller/waFrontController.class.php(58): waFrontController->execute('yamodule_api', 'settings', NULL)
#8 wa-system/waSystem.class.php(562): waFrontController->dispatch()
#9 wa-system/waSystem.class.php(485): waSystem->dispatchBackend('webasyst/shop/')
#10 index.php(7): waSystem->dispatch()
#11 {main}
/home/s/seosheks/sheerdecor.ru/public_html/wa-system/database/waModel.class.php around line 257
252	                "Query Error %d: %s\nQuery: %s",
   253	                $this->adapter->errorCode(),
   254	                $this->adapter->error(),
   255	                $sql
   256	            );
 >>257	            throw new waDbException($error, $this->adapter->errorCode());
   258	        }
   259	        return $result;
   260	    }
   261	
   262	    /**
GET
array(
  'plugin' => 'yamodule_api',
  'module' => 'settings',
  '_' => '1532415365757',
)
Params
array()
```

PHP Version 5.6.30

**Comment by lustmordtheblackpost** [comment]
+ Undefined variable: sql2 in /wa-apps/shop/plugins/yamodule_api/lib/config/install.php on line 27
